# Generated by Django 4.0.5 on 2022-06-21 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.AlterModelOptions(
            name='customerrequest',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'Ministries'},
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='ministry_name',
            new_name='ministry',
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.requeststatus'),
        ),
    ]
