# Generated by Django 4.0.5 on 2022-06-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_requeststatus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRequestComment',
        ),
    ]
