# Generated by Django 4.0.5 on 2022-06-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_customerrequestcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='customer_telephone',
            field=models.CharField(help_text='468-5050 or 456-5050', max_length=50),
        ),
    ]
